In [12]:
import pandas as pd

#I'm using a dataset other than the titanic one
NYSP = 'NY_stock_price.csv'

# Load the dataset into a DataFrame
df = pd.read_csv(NYSP)
df.isna().sum()

Unnamed: 0                        0
Ticker Symbol                     0
Period Ending                     0
Accounts Payable                  0
Accounts Receivable               0
                               ...
Total Revenue                     0
Treasury Stock                    0
For Year                        173
Earnings Per Share              219
Estimated Shares Outstanding    219
Length: 79, dtype: int64

In [13]:
df.shape

(1781, 79)

Obeservation are rows in the dataset. In my dataset, they represent each company's stock price prediction in New York.

Variables are columns in the dataset, representing different attributes or characteristics that can be measured or recorded for each observation. In my dataset, they record the companys' Ticker Symbol,Period Ending,Accounts Payable,Accounts Receivable,Add'l income/expense items,After Tax ROE,Capital Expenditures,Capital Surplus,Cash Ratio,Cash and Cash Equivalents,Changes in Inventories,Common Stocks,Cost of Revenue,Current Ratio,Deferred Asset Charges,Deferred Liability Charges,Depreciation,Earnings Before Interest and Tax,Earnings Before Tax,Effect of Exchange Rate,Equity Earnings/Loss Unconsolidated Subsidiary,Fixed Assets,Goodwill,Gross Margin,Gross Profit,Income Tax,Intangible Assets,Interest Expense,Inventory,Investments,Liabilities,Long-Term Debt,Long-Term Investments,Minority Interest,Misc. Stocks,Net Borrowings,Net Cash Flow,Net Cash Flow-Operating,Net Cash Flows-Financing,Net Cash Flows-Investing,Net Income,Net Income Adjustments,Net Income Applicable to Common Shareholders,Net Income-Cont. Operations,Net Receivables,Non-Recurring Items,Operating Income,Operating Margin,Other Assets,Other Current Assets,Other Current Liabilities,Other Equity,Other Financing Activities,Other Investing Activities,Other Liabilities,Other Operating Activities,Other Operating Items,Pre-Tax Margin,Pre-Tax ROE,Profit Margin,Quick Ratio,Research and Development,Retained Earnings,Sale and Purchase of Stock,"Sales, General and Admin.",Short-Term Debt / Current Portion of Long-Term Debt,Short-Term Investments,Total Assets,Total Current Assets,Total Current Liabilities,Total Equity,Total Liabilities,Total Liabilities & Equity,Total Revenue,Treasury Stock,For Year,Earnings Per Share,Estimated Shares Outstanding

In [14]:
# Display the first few rows of the DataFrame to understand its structure
print("First few rows of the dataset:")
print(df.head())

First few rows of the dataset:
   Unnamed: 0 Ticker Symbol Period Ending  Accounts Payable  \
0           0           AAL    2012-12-31      3.068000e+09
1           1           AAL    2013-12-31      4.975000e+09
2           2           AAL    2014-12-31      4.668000e+09
3           3           AAL    2015-12-31      5.102000e+09
4           4           AAP    2012-12-29      2.409453e+09

   Accounts Receivable  Add'l income/expense items  After Tax ROE  \
0         -222000000.0               -1.961000e+09           23.0
1          -93000000.0               -2.723000e+09           67.0
2         -160000000.0               -1.500000e+08          143.0
3          352000000.0               -7.080000e+08          135.0
4          -89482000.0                6.000000e+05           32.0

   Capital Expenditures  Capital Surplus  Cash Ratio  ...  \
0         -1.888000e+09     4.695000e+09        53.0  ...
1         -3.114000e+09     1.059200e+10        75.0  ...
2         -5.311000e+09     1.513500e+10        60.0  ...
3         -6.151000e+09     1.159100e+10        51.0  ...
4         -2.711820e+08     5.202150e+08        23.0  ...

   Total Current Assets  Total Current Liabilities  Total Equity  \
0          7.072000e+09               9.011000e+09 -7.987000e+09
1          1.432300e+10               1.380600e+10 -2.731000e+09
2          1.175000e+10               1.340400e+10  2.021000e+09
3          9.985000e+09               1.360500e+10  5.635000e+09
4          3.184200e+09               2.559638e+09  1.210694e+09

   Total Liabilities  Total Liabilities & Equity  Total Revenue  \
0       2.489100e+10                1.690400e+10   2.485500e+10
1       4.500900e+10                4.227800e+10   2.674300e+10
2       4.120400e+10                4.322500e+10   4.265000e+10
3       4.278000e+10                4.841500e+10   4.099000e+10
4       3.403120e+09                4.613814e+09   6.205003e+09

   Treasury Stock  For Year  Earnings Per Share  Estimated Shares Outstanding
0    -367000000.0    2012.0               -5.60                  3.350000e+08
1             0.0    2013.0              -11.25                  1.630222e+08
2             0.0    2014.0                4.02                  7.169154e+08
3             0.0    2015.0               11.39                  6.681299e+08
4     -27095000.0    2012.0                5.29                  7.328355e+07

[5 rows x 79 columns]

In [15]:
# Summary statistics for numeric columns
print("\nSummary statistics for numeric columns:")
print(df.describe())

Summary statistics for numeric columns:
        Unnamed: 0  Accounts Payable  Accounts Receivable  \
count  1781.000000      1.781000e+03         1.781000e+03
mean    890.000000      4.673418e+09        -6.353484e+07
std     514.274732      1.406047e+10         7.562794e+08
min       0.000000      0.000000e+00        -6.452000e+09
25%     445.000000      5.160000e+08        -1.040000e+08
50%     890.000000      1.334000e+09        -1.830000e+07
75%    1335.000000      3.246000e+09         7.816000e+06
max    1780.000000      2.069390e+11         2.266400e+10

       Add'l income/expense items  After Tax ROE  Capital Expenditures  \
count                1.781000e+03    1781.000000          1.781000e+03
mean                 6.908940e+07      43.601348         -1.251925e+09
std                  6.848143e+08     233.924028          2.979963e+09
min                 -6.768000e+09       0.000000         -3.798500e+10
25%                 -2.638000e+06      10.000000         -1.151200e+09
50%                  2.000000e+06      16.000000         -3.580000e+08
75%                  3.359200e+07      26.000000         -1.291000e+08
max                  1.416200e+10    5789.000000          5.000000e+06

       Capital Surplus   Cash Ratio  Cash and Cash Equivalents  \
count     1.781000e+03  1482.000000               1.781000e+03
mean      5.351784e+09    74.457490               8.521399e+09
std       1.133977e+10   102.298374               5.432105e+10
min      -7.215000e+08     0.000000               2.100000e+04
25%       4.791000e+08    17.000000               3.088000e+08
50%       1.997080e+09    41.000000               8.625900e+08
75%       5.735000e+09    90.000000               2.310000e+09
max       1.082880e+11  1041.000000               7.281110e+11

       Changes in Inventories  ...  Total Current Assets  \
count            1.781000e+03  ...          1.781000e+03
mean            -6.787749e+07  ...          6.726349e+09
std              3.903369e+08  ...          1.344800e+10
min             -5.562000e+09  ...          0.000000e+00
25%             -5.400000e+07  ...          1.044178e+09
50%              0.000000e+00  ...          2.747200e+09
75%              0.000000e+00  ...          6.162000e+09
max              3.755000e+09  ...          1.396600e+11

       Total Current Liabilities  Total Equity  Total Liabilities  \
count               1.781000e+03  1.781000e+03       1.781000e+03
mean                4.699919e+09  1.188846e+10       4.380420e+10
std                 9.538832e+09  2.584429e+10       1.817039e+11
min                 0.000000e+00 -1.324400e+10       2.577000e+06
25%                 5.640760e+08  2.201492e+09       3.843300e+09
50%                 1.701500e+09  4.983000e+09       9.141000e+09
75%                 4.381000e+09  1.080900e+10       2.389700e+10
max                 9.028100e+10  2.562050e+11       2.340547e+12

       Total Liabilities & Equity  Total Revenue  Treasury Stock     For Year  \
count                1.781000e+03   1.781000e+03    1.781000e+03  1608.000000
mean                 5.569266e+10   2.029154e+10   -3.951522e+09  2013.305348
std                  2.033612e+11   4.095355e+10    1.407047e+10    19.953135
min                  2.705000e+06   1.514000e+06   -2.297340e+11  1215.000000
25%                  6.552689e+09   3.714000e+09   -3.040895e+09  2013.000000
50%                  1.517000e+10   8.023200e+09   -3.068350e+08  2014.000000
75%                  3.599710e+10   1.748600e+10    0.000000e+00  2015.000000
max                  2.572274e+12   4.856510e+11    0.000000e+00  2016.000000

       Earnings Per Share  Estimated Shares Outstanding
count         1562.000000                  1.562000e+03
mean             3.353707                  6.024244e+08
std              4.695896                  1.142585e+09
min            -61.200000                 -1.513945e+09
25%              1.590000                  1.493318e+08
50%              2.810000                  2.929409e+08
75%              4.590000                  5.492163e+08
max             50.090000                  1.610769e+10

[8 rows x 77 columns]

In [16]:
# Identify and display value counts for all categorical columns
categorical_columns = df.select_dtypes(include=['object']).columns
print("\nValue counts for all categorical columns:")
for column in categorical_columns:
    print(f"\nValue counts for {column}:")
    print(df[column].value_counts())

Value counts for all categorical columns:

Value counts for Ticker Symbol:
Ticker Symbol
AAL     4
NOV     4
OMC     4
OKE     4
O       4
       ..
PYPL    3
WRK     3
AVGO    2
MYL     2
CSRA    2
Name: count, Length: 448, dtype: int64

Value counts for Period Ending:
Period Ending
2014-12-31    317
2015-12-31    317
2013-12-31    316
2012-12-31    225
2016-12-31     97
             ...
2007-02-28      1
2006-02-28      1
2004-06-30      1
2003-06-30      1
2013-10-03      1
Name: count, Length: 162, dtype: int64

In [17]:
# Check for missing values in numeric columns
print("\nMissing values in numeric columns:")
print(df.select_dtypes(include=['float64', 'int64']).isna().sum())

Missing values in numeric columns:
Unnamed: 0                        0
Accounts Payable                  0
Accounts Receivable               0
Add'l income/expense items        0
After Tax ROE                     0
                               ...
Total Revenue                     0
Treasury Stock                    0
For Year                        173
Earnings Per Share              219
Estimated Shares Outstanding    219
Length: 77, dtype: int64

In [18]:
# Include a more comprehensive summary that includes all columns
print("\nComprehensive descriptive statistics:")
print(df.describe(include='all'))

Comprehensive descriptive statistics:
         Unnamed: 0 Ticker Symbol Period Ending  Accounts Payable  \
count   1781.000000          1781          1781      1.781000e+03
unique          NaN           448           162               NaN
top             NaN           AAL    2014-12-31               NaN
freq            NaN             4           317               NaN
mean     890.000000           NaN           NaN      4.673418e+09
std      514.274732           NaN           NaN      1.406047e+10
min        0.000000           NaN           NaN      0.000000e+00
25%      445.000000           NaN           NaN      5.160000e+08
50%      890.000000           NaN           NaN      1.334000e+09
75%     1335.000000           NaN           NaN      3.246000e+09
max     1780.000000           NaN           NaN      2.069390e+11

        Accounts Receivable  Add'l income/expense items  After Tax ROE  \
count          1.781000e+03                1.781000e+03    1781.000000
unique                  NaN                         NaN            NaN
top                     NaN                         NaN            NaN
freq                    NaN                         NaN            NaN
mean          -6.353484e+07                6.908940e+07      43.601348
std            7.562794e+08                6.848143e+08     233.924028
min           -6.452000e+09               -6.768000e+09       0.000000
25%           -1.040000e+08               -2.638000e+06      10.000000
50%           -1.830000e+07                2.000000e+06      16.000000
75%            7.816000e+06                3.359200e+07      26.000000
max            2.266400e+10                1.416200e+10    5789.000000

        Capital Expenditures  Capital Surplus   Cash Ratio  ...  \
count           1.781000e+03     1.781000e+03  1482.000000  ...
unique                   NaN              NaN          NaN  ...
top                      NaN              NaN          NaN  ...
freq                     NaN              NaN          NaN  ...
mean           -1.251925e+09     5.351784e+09    74.457490  ...
std             2.979963e+09     1.133977e+10   102.298374  ...
min            -3.798500e+10    -7.215000e+08     0.000000  ...
25%            -1.151200e+09     4.791000e+08    17.000000  ...
50%            -3.580000e+08     1.997080e+09    41.000000  ...
75%            -1.291000e+08     5.735000e+09    90.000000  ...
max             5.000000e+06     1.082880e+11  1041.000000  ...

        Total Current Assets  Total Current Liabilities  Total Equity  \
count           1.781000e+03               1.781000e+03  1.781000e+03
unique                   NaN                        NaN           NaN
top                      NaN                        NaN           NaN
freq                     NaN                        NaN           NaN
mean            6.726349e+09               4.699919e+09  1.188846e+10
std             1.344800e+10               9.538832e+09  2.584429e+10
min             0.000000e+00               0.000000e+00 -1.324400e+10
25%             1.044178e+09               5.640760e+08  2.201492e+09
50%             2.747200e+09               1.701500e+09  4.983000e+09
75%             6.162000e+09               4.381000e+09  1.080900e+10
max             1.396600e+11               9.028100e+10  2.562050e+11

        Total Liabilities  Total Liabilities & Equity  Total Revenue  \
count        1.781000e+03                1.781000e+03   1.781000e+03
unique                NaN                         NaN            NaN
top                   NaN                         NaN            NaN
freq                  NaN                         NaN            NaN
mean         4.380420e+10                5.569266e+10   2.029154e+10
std          1.817039e+11                2.033612e+11   4.095355e+10
min          2.577000e+06                2.705000e+06   1.514000e+06
25%          3.843300e+09                6.552689e+09   3.714000e+09
50%          9.141000e+09                1.517000e+10   8.023200e+09
75%          2.389700e+10                3.599710e+10   1.748600e+10
max          2.340547e+12                2.572274e+12   4.856510e+11

        Treasury Stock     For Year  Earnings Per Share  \
count     1.781000e+03  1608.000000         1562.000000
unique             NaN          NaN                 NaN
top                NaN          NaN                 NaN
freq               NaN          NaN                 NaN
mean     -3.951522e+09  2013.305348            3.353707
std       1.407047e+10    19.953135            4.695896
min      -2.297340e+11  1215.000000          -61.200000
25%      -3.040895e+09  2013.000000            1.590000
50%      -3.068350e+08  2014.000000            2.810000
75%       0.000000e+00  2015.000000            4.590000
max       0.000000e+00  2016.000000           50.090000

        Estimated Shares Outstanding
count                   1.562000e+03
unique                           NaN
top                              NaN
freq                             NaN
mean                    6.024244e+08
std                     1.142585e+09
min                    -1.513945e+09
25%                     1.493318e+08
50%                     2.929409e+08
75%                     5.492163e+08
max                     1.610769e+10

[11 rows x 79 columns]

(a) Number of columns anaylzed:
    
    df.shape: This attribute gives me the total number of rows and columns in the DataFrame. It counts all columns, regardless of the data type—numeric, categorical, or otherwise.
    
    df.describe(): This method only provides a summary for columns with numeric data types. These summaries include statistics such as mean, standard deviation, minimum, maximum, and quartiles. If my DataFrame contains non-numeric (e.g., categorical or boolean) columns, these will not be included in the describe() output

(b)Values Reported in the "Count" Column
    
    Count in df.describe(): In the output of df.describe(), the "count" row indicates the number of non-null (i.e., non-missing) entries for each numeric column included in the summary. If there are missing values in any of these columns, the count will be less than the total number of rows as reported by df.shape[0]. This discrepancy occurs because describe() automatically excludes null values when computing the statistics.

An attribute refers to the variables or data of an object. A method is a function that can be used to modify the data of an object or a class.

Count: The number of non-missing values in the column. This count does not include NaN (not a number) values.

Mean: The average of the values in the column. It is calculated by summing all the values and dividing by the count of non-missing values.

Std (Standard Deviation): A measure of the amount of variation or dispersion of a set of values. A low standard deviation indicates that the values tend to be close to the mean, while a high standard deviation indicates that the values are spread out over a wider range.

Min (Minimum): The smallest value in the column.

25% (25th Percentile): The value below which 25% of the data falls. It is also known as the first quartile.

50% (50th Percentile or Median): The value below which 50% of the data falls. It is the middle value of the dataset, and if the number of observations is even, it is the average of the two middle numbers.

75% (75th Percentile): The value below which 75% of the data falls. It is also known as the third quartile.

Max (Maximum): The largest value in the column.

(a) an example of a "use case" in which using df.dropna() might be peferred over using del df['col']:
    When we have a dataset with a few columns where missing values are sporadic but crucial, for example, a dataset tracking stock prices where certain dates have missing values. In this case, df.dropna() might be preferred as we would want to remove rows where any column has missing data.
    
(b) When we have a dataset with a column having a significant amount of missing data compared to other columns. For example, if there is a ColumnX which is not critical but has a lot of missing data, removing this column using del df['col'] might be preferred.

(c) When using both methods together, applying del df['col'] before df.dropna() can be important because removing columns with too many missing values first can reduce the number of rows that df.dropna() might need to process. Furthermore, by dropping irrelevant or excessively missing columns first, we will be able to ensure that df.dropna() focuses only on the remaining data.

In [19]:
# (d) 
# Display basic info about the dataset before cleaning
print("Before cleaning:")
print(df.info())
print("\nMissing data before cleaning:")
print(df.isnull().sum())

#Example: Removing a column with significant missing data
column_to_remove = 'Estimated Shares Outstanding'
if column_to_remove in df.columns:
    del df[column_to_remove]

# Alternatively, drop rows with any missing values
df_cleaned = df.dropna()

# Display basic info about the dataset after cleaning
print("\nAfter cleaning:")
print(df_cleaned.info())
print("\nMissing data after cleaning:")
print(df_cleaned.isnull().sum())

Before cleaning:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1781 entries, 0 to 1780
Data columns (total 79 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Unnamed: 0                                           1781 non-null   int64
 1   Ticker Symbol                                        1781 non-null   object
 2   Period Ending                                        1781 non-null   object
 3   Accounts Payable                                     1781 non-null   float64
 4   Accounts Receivable                                  1781 non-null   float64
 5   Add'l income/expense items                           1781 non-null   float64
 6   After Tax ROE                                        1781 non-null   float64
 7   Capital Expenditures                                 1781 non-null   float64
 8   Capital Surplus                                      1781 non-null   float64
 9   Cash Ratio                                           1482 non-null   float64
 10  Cash and Cash Equivalents                            1781 non-null   float64
 11  Changes in Inventories                               1781 non-null   float64
 12  Common Stocks                                        1781 non-null   float64
 13  Cost of Revenue                                      1781 non-null   float64
 14  Current Ratio                                        1482 non-null   float64
 15  Deferred Asset Charges                               1781 non-null   float64
 16  Deferred Liability Charges                           1781 non-null   float64
 17  Depreciation                                         1781 non-null   float64
 18  Earnings Before Interest and Tax                     1781 non-null   float64
 19  Earnings Before Tax                                  1781 non-null   float64
 20  Effect of Exchange Rate                              1781 non-null   float64
 21  Equity Earnings/Loss Unconsolidated Subsidiary       1781 non-null   float64
 22  Fixed Assets                                         1781 non-null   float64
 23  Goodwill                                             1781 non-null   float64
 24  Gross Margin                                         1781 non-null   float64
 25  Gross Profit                                         1781 non-null   float64
 26  Income Tax                                           1781 non-null   float64
 27  Intangible Assets                                    1781 non-null   float64
 28  Interest Expense                                     1781 non-null   float64
 29  Inventory                                            1781 non-null   float64
 30  Investments                                          1781 non-null   float64
 31  Liabilities                                          1781 non-null   float64
 32  Long-Term Debt                                       1781 non-null   float64
 33  Long-Term Investments                                1781 non-null   float64
 34  Minority Interest                                    1781 non-null   float64
 35  Misc. Stocks                                         1781 non-null   float64
 36  Net Borrowings                                       1781 non-null   float64
 37  Net Cash Flow                                        1781 non-null   float64
 38  Net Cash Flow-Operating                              1781 non-null   float64
 39  Net Cash Flows-Financing                             1781 non-null   float64
 40  Net Cash Flows-Investing                             1781 non-null   float64
 41  Net Income                                           1781 non-null   float64
 42  Net Income Adjustments                               1781 non-null   float64
 43  Net Income Applicable to Common Shareholders         1781 non-null   float64
 44  Net Income-Cont. Operations                          1781 non-null   float64
 45  Net Receivables                                      1781 non-null   float64
 46  Non-Recurring Items                                  1781 non-null   float64
 47  Operating Income                                     1781 non-null   float64
 48  Operating Margin                                     1781 non-null   float64
 49  Other Assets                                         1781 non-null   float64
 50  Other Current Assets                                 1781 non-null   float64
 51  Other Current Liabilities                            1781 non-null   float64
 52  Other Equity                                         1781 non-null   float64
 53  Other Financing Activities                           1781 non-null   float64
 54  Other Investing Activities                           1781 non-null   float64
 55  Other Liabilities                                    1781 non-null   float64
 56  Other Operating Activities                           1781 non-null   float64
 57  Other Operating Items                                1781 non-null   float64
 58  Pre-Tax Margin                                       1781 non-null   float64
 59  Pre-Tax ROE                                          1781 non-null   float64
 60  Profit Margin                                        1781 non-null   float64
 61  Quick Ratio                                          1482 non-null   float64
 62  Research and Development                             1781 non-null   float64
 63  Retained Earnings                                    1781 non-null   float64
 64  Sale and Purchase of Stock                           1781 non-null   float64
 65  Sales, General and Admin.                            1781 non-null   float64
 66  Short-Term Debt / Current Portion of Long-Term Debt  1781 non-null   float64
 67  Short-Term Investments                               1781 non-null   float64
 68  Total Assets                                         1781 non-null   float64
 69  Total Current Assets                                 1781 non-null   float64
 70  Total Current Liabilities                            1781 non-null   float64
 71  Total Equity                                         1781 non-null   float64
 72  Total Liabilities                                    1781 non-null   float64
 73  Total Liabilities & Equity                           1781 non-null   float64
 74  Total Revenue                                        1781 non-null   float64
 75  Treasury Stock                                       1781 non-null   float64
 76  For Year                                             1608 non-null   float64
 77  Earnings Per Share                                   1562 non-null   float64
 78  Estimated Shares Outstanding                         1562 non-null   float64
dtypes: float64(76), int64(1), object(2)
memory usage: 1.1+ MB
None

Missing data before cleaning:
Unnamed: 0                        0
Ticker Symbol                     0
Period Ending                     0
Accounts Payable                  0
Accounts Receivable               0
                               ...
Total Revenue                     0
Treasury Stock                    0
For Year                        173
Earnings Per Share              219
Estimated Shares Outstanding    219
Length: 79, dtype: int64

After cleaning:
<class 'pandas.core.frame.DataFrame'>
Index: 1299 entries, 0 to 1779
Data columns (total 78 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Unnamed: 0                                           1299 non-null   int64
 1   Ticker Symbol                                        1299 non-null   object
 2   Period Ending                                        1299 non-null   object
 3   Accounts Payable                                     1299 non-null   float64
 4   Accounts Receivable                                  1299 non-null   float64
 5   Add'l income/expense items                           1299 non-null   float64
 6   After Tax ROE                                        1299 non-null   float64
 7   Capital Expenditures                                 1299 non-null   float64
 8   Capital Surplus                                      1299 non-null   float64
 9   Cash Ratio                                           1299 non-null   float64
 10  Cash and Cash Equivalents                            1299 non-null   float64
 11  Changes in Inventories                               1299 non-null   float64
 12  Common Stocks                                        1299 non-null   float64
 13  Cost of Revenue                                      1299 non-null   float64
 14  Current Ratio                                        1299 non-null   float64
 15  Deferred Asset Charges                               1299 non-null   float64
 16  Deferred Liability Charges                           1299 non-null   float64
 17  Depreciation                                         1299 non-null   float64
 18  Earnings Before Interest and Tax                     1299 non-null   float64
 19  Earnings Before Tax                                  1299 non-null   float64
 20  Effect of Exchange Rate                              1299 non-null   float64
 21  Equity Earnings/Loss Unconsolidated Subsidiary       1299 non-null   float64
 22  Fixed Assets                                         1299 non-null   float64
 23  Goodwill                                             1299 non-null   float64
 24  Gross Margin                                         1299 non-null   float64
 25  Gross Profit                                         1299 non-null   float64
 26  Income Tax                                           1299 non-null   float64
 27  Intangible Assets                                    1299 non-null   float64
 28  Interest Expense                                     1299 non-null   float64
 29  Inventory                                            1299 non-null   float64
 30  Investments                                          1299 non-null   float64
 31  Liabilities                                          1299 non-null   float64
 32  Long-Term Debt                                       1299 non-null   float64
 33  Long-Term Investments                                1299 non-null   float64
 34  Minority Interest                                    1299 non-null   float64
 35  Misc. Stocks                                         1299 non-null   float64
 36  Net Borrowings                                       1299 non-null   float64
 37  Net Cash Flow                                        1299 non-null   float64
 38  Net Cash Flow-Operating                              1299 non-null   float64
 39  Net Cash Flows-Financing                             1299 non-null   float64
 40  Net Cash Flows-Investing                             1299 non-null   float64
 41  Net Income                                           1299 non-null   float64
 42  Net Income Adjustments                               1299 non-null   float64
 43  Net Income Applicable to Common Shareholders         1299 non-null   float64
 44  Net Income-Cont. Operations                          1299 non-null   float64
 45  Net Receivables                                      1299 non-null   float64
 46  Non-Recurring Items                                  1299 non-null   float64
 47  Operating Income                                     1299 non-null   float64
 48  Operating Margin                                     1299 non-null   float64
 49  Other Assets                                         1299 non-null   float64
 50  Other Current Assets                                 1299 non-null   float64
 51  Other Current Liabilities                            1299 non-null   float64
 52  Other Equity                                         1299 non-null   float64
 53  Other Financing Activities                           1299 non-null   float64
 54  Other Investing Activities                           1299 non-null   float64
 55  Other Liabilities                                    1299 non-null   float64
 56  Other Operating Activities                           1299 non-null   float64
 57  Other Operating Items                                1299 non-null   float64
 58  Pre-Tax Margin                                       1299 non-null   float64
 59  Pre-Tax ROE                                          1299 non-null   float64
 60  Profit Margin                                        1299 non-null   float64
 61  Quick Ratio                                          1299 non-null   float64
 62  Research and Development                             1299 non-null   float64
 63  Retained Earnings                                    1299 non-null   float64
 64  Sale and Purchase of Stock                           1299 non-null   float64
 65  Sales, General and Admin.                            1299 non-null   float64
 66  Short-Term Debt / Current Portion of Long-Term Debt  1299 non-null   float64
 67  Short-Term Investments                               1299 non-null   float64
 68  Total Assets                                         1299 non-null   float64
 69  Total Current Assets                                 1299 non-null   float64
 70  Total Current Liabilities                            1299 non-null   float64
 71  Total Equity                                         1299 non-null   float64
 72  Total Liabilities                                    1299 non-null   float64
 73  Total Liabilities & Equity                           1299 non-null   float64
 74  Total Revenue                                        1299 non-null   float64
 75  Treasury Stock                                       1299 non-null   float64
 76  For Year                                             1299 non-null   float64
 77  Earnings Per Share                                   1299 non-null   float64
dtypes: float64(75), int64(1), object(2)
memory usage: 801.7+ KB
None

Missing data after cleaning:
Unnamed: 0                    0
Ticker Symbol                 0
Period Ending                 0
Accounts Payable              0
Accounts Receivable           0
                             ..
Total Liabilities & Equity    0
Total Revenue                 0
Treasury Stock                0
For Year                      0
Earnings Per Share            0
Length: 78, dtype: int64

Justification of approach: I use del to remove the column 'Estimated Shares Outstanding' because it has a lot of missing values and is not that relevant to the analysis. After removing irrelevant columns, I use df.dropna() to remove rows with any missing values in the remaining columns.

1.First, df.groupby("col1")["col2"].describe() will classify and group "col2" according to "col1". Then, the function will describe and calculate the count, mean, standard deviation, minimum, Q1, median, Q3, and maximum value of "col2". For example, in the dataset I'm using, let's take "Ticker Symbol" as 'col1' and "Cash Ratio" as 'col2'. df.groupby('Ticker Symbol')['Cash Ratio'].describe() will get me descriptive statistics for the Cash Ratio column, grouped by Ticker Symbol. The following will be a demo

In [20]:
df.groupby('Ticker Symbol')['Cash Ratio'].describe()

               count    mean         std    min     25%    50%     75%    max
Ticker Symbol
AAL              4.0   59.75   10.874282   51.0   52.50   56.5   63.75   75.0
AAP              4.0   17.00   18.129166    2.0    2.75   13.0   27.25   40.0
AAPL             4.0   67.50   25.514702   40.0   49.00   68.5   87.00   93.0
ABBV             4.0  103.25   33.777458   74.0   76.25   97.5  124.50  144.0
ABC              4.0    9.75    1.258306    8.0    9.50   10.0   10.25   11.0
...              ...     ...         ...    ...     ...    ...     ...    ...
YHOO             4.0  303.50  119.795659  177.0  234.75  289.0  357.75  459.0
YUM              4.0   31.25    5.965177   27.0   27.75   29.0   32.50   40.0
ZBH              4.0  155.25   37.286056  100.0  149.50  170.5  176.25  180.0
ZION             0.0     NaN         NaN    NaN     NaN    NaN     NaN    NaN
ZTS              4.0   63.50   15.609826   43.0   59.50   65.0   69.00   81.0

[448 rows x 8 columns]

2.for df.describe(), the count shows how many valid entries exist in each column across the entire dataset. Missing values in any column will reduce this count compared to the total number of rows. On the other hand, for df.groupby("col1")["col2"].describe(), the count shows how many valid entries exist in col2 for each subgroup defined by col1. This can vary depending on how many valid entries of col2 are present within each group. If a group has missing values in col2, its count will be lower, but this count is specific to that subgroup. df.describe() provides an overall picture of the dataset’s completeness for each column, while df.groupby("col1")["col2"].describe() provides insights into the completeness of col2 within each subgroup defined by col1, which can vary depending on how the data is grouped.

In [1]:
#Part A
URL = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"

# Load the dataset into a DataFrame
df = pd.read_csv(URL)
df.isna().sum()

NameError: name 'pd' is not defined

ChatGPT is more useful as it quickly recognizes my error and can provide me with the code to fix the issue.

In [2]:
#Part B
import pandas as pd
URL = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanics.csv"

# Load the dataset into a DataFrame
df = pd.read_csv(URL)
df.isna().sum()

HTTPError: HTTP Error 404: Not Found

ChatGPT is more useful as it quickly recognizes my error and can even provide me with the code including a correct URL.

In [3]:
#Part C
import pandas as pd
URL = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"

# Load the dataset into a DataFrame
df = pd.read_csv(URL)
df.isna().sum()

DF.groupby("sex")["age"].describe()

NameError: name 'DF' is not defined

ChatGPT is more useful as it quickly recognizes my error and can provide me with the code to fix the issue. On the other hand, google only tells how to solve this under a general case but cannot give me the correct code directly.

In [4]:
#Part D
import pandas as pd
URL = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"

# Load the dataset into a DataFrame
df = pd.read_csv(URL
df.isna().sum()

df.groupby("sex")["age"].describe()

SyntaxError: '(' was never closed (68485042.py, line 6)

ChatGPT is more useful as it quickly recognizes my error and can provide me with the code with complete parethesis. I can just copy-paste my new code to fix the issue. Google cannot tell me specifically what my mistake is and can only tells how to solve this under a general case.

In [5]:
#Part E
import pandas as pd
URL = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"

# Load the dataset into a DataFrame
df = pd.read_csv(URL)
df.isna().sum()

df.group_by("sex")["age"].describe()

AttributeError: 'DataFrame' object has no attribute 'group_by'

ChatGPT is more useful as it quickly recognizes my error and can provide me with the right code. Google doesn't read my code thus cannot tell me specifically what my mistake is and can only tells how to solve this under a general case

In [6]:
#Part F
import pandas as pd
URL = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"

# Load the dataset into a DataFrame
df = pd.read_csv(URL)
df.isna().sum()

df.groupby("Sex")["age"].describe()

KeyError: 'Sex'

ChatGPT is more useful as it quickly recognizes my error, read my csv, and can provide me with the right code with the right column name. Google cannot read my csv and resolve my issue under this specific case.

In [7]:
#Part G
import pandas as pd
URL = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"

# Load the dataset into a DataFrame
df = pd.read_csv(URL)
df.isna().sum()

df.groupby(sex)["age"].describe()

NameError: name 'sex' is not defined

ChatGPT is more useful as it quickly recognizes my error and can provide me with the right code with the quotation marks. Google cannot tell me specifically what my mistake is and can only tells how to solve this under a general case.

Yes, I have reviewed the course wiki-textbook and interacted with a ChatBot to help me understand.

My links of my interaction with ChatGPT:
https://chatgpt.com/share/66e3a3de-0e94-8004-9730-706cd95d7e39
https://chatgpt.com/share/66e3a403-ec6c-8004-8cfb-b66713c116d2